CREATE TABLE depts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    parent_id BIGINT UNSIGNED DEFAULT NULL,
    name VARCHAR(100) NOT NULL,
    leader VARCHAR(100) DEFAULT NULL,
    phone VARCHAR(20) DEFAULT NULL,
    email VARCHAR(191) DEFAULT NULL,
    sort INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_depts_parent_id (parent_id),
    CONSTRAINT fk_depts_parent FOREIGN KEY (parent_id) REFERENCES depts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE users
    ADD COLUMN dept_id BIGINT UNSIGNED DEFAULT NULL AFTER phone,
    ADD KEY idx_users_dept_id (dept_id),
    ADD CONSTRAINT fk_users_dept FOREIGN KEY (dept_id) REFERENCES depts(id) ON DELETE SET NULL;
